---
- name: apt-get apache2 install
  apt: pkg={{ item }}
       force=yes
       update_cache=yes
  with_items:
   - apache2
   - libapache2-mod-php5
   - phpmyadmin
  tags: apache2

- name: enable mod_rewrite
  shell: a2enmod rewrite
  tags: apache2

- name: start apache2 service
  service:
    name: apache2
    state: started
    enabled: yes
  tags: apache2
