---
- name: apt-get php install
  apt: pkg={{ item }}
       force=yes
       update_cache=yes
  with_items:
   - php5
   - php5-cli
   - php5-common
   - php5-curl
   - php5-gd
   - php5-imagick
   - php5-mysql
   - php5-xmlrpc
   - php5-mcrypt
   - php-apc
  tags: php
